import React, { useMemo, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { CalendarDays, ChevronRight, Clock3, MapPin, Search, Ticket, User, X, Check, ArrowLeft, Film, Building2 } from 'lucide-react'
import './styles.css'

const movies=[
{id:'aravindha-sametha',title:'Aravindha Sametha',year:'2018',language:'Telugu',genre:'Action · Drama',tone:'red'},
{id:'dragon',title:'Dragon',year:'2026',language:'Telugu',genre:'Action · Drama',tone:'gold'},
{id:'simhadri',title:'Simhadri',year:'2003',language:'Telugu',genre:'Action · Drama',tone:'crimson'},
{id:'brindhavanam',title:'Brindhavanam',year:'2010',language:'Telugu',genre:'Romance · Comedy',tone:'green'},
{id:'spirit',title:'Spirit',year:'2026',language:'Telugu',genre:'Action · Crime',tone:'violet'},
{id:'ms-dhoni',title:'M.S. Dhoni',year:'2016',language:'Hindi',genre:'Biography · Sport',tone:'blue'},
{id:'varanasi',title:'Varanasi',year:'2026',language:'Telugu',genre:'Action · Fantasy',tone:'orange'}]
const theaters=[
{id:'ar-tenali',name:'AR Theatre',city:'Tenali',state:'Andhra Pradesh',type:'Portie Best Screen',formats:['2D','Dolby 7.1'],price:180},
{id:'sangameshwara',name:'Sangameshwara',city:'Tenali',state:'Andhra Pradesh',type:'Portie Best Screen',formats:['2D','Dolby 7.1'],price:180},
{id:'ar-kukatpally',name:'AR Theatre',city:'Kukatpally',state:'Telangana',type:'Metro Premium Screen',formats:['2D','Dolby Atmos'],price:260},
{id:'ar-madhapur',name:'AR Theatre',city:'Madhapur',state:'Telangana',type:'IMAX-style Premium',formats:['IMAX','Dolby Atmos'],price:380},
{id:'sudharshan',name:'Sudharshan 35MM',city:'Hyderabad',state:'Telangana',type:'Classic City Screen',formats:['2D','Dolby Atmos'],price:220},
{id:'vimal',name:'Vimal Theatre',city:'Hyderabad',state:'Telangana',type:'Premium Screen',formats:['2D','Dolby 7.1'],price:240},
{id:'prasad',name:'Prasads IMAX',city:'Hyderabad',state:'Telangana',type:'IMAX',formats:['IMAX','2D'],price:350},
{id:'ar-vijayawada',name:'AR Theatre',city:'Vijayawada',state:'Andhra Pradesh',type:'Portie Best Screen',formats:['2D','Dolby 7.1'],price:210},
{id:'ar-guntur',name:'AR Theatre',city:'Guntur',state:'Andhra Pradesh',type:'Portie Best Screen',formats:['2D','Dolby 7.1'],price:200},
{id:'ar-visakhapatnam',name:'AR Theatre',city:'Visakhapatnam',state:'Andhra Pradesh',type:'IMAX-style Premium',formats:['IMAX','Dolby Atmos'],price:340},
{id:'ar-bengaluru',name:'AR Theatre',city:'Bengaluru',state:'Karnataka',type:'IMAX-style Metro Screen',formats:['2D','Dolby Atmos'],price:320},
{id:'ar-chennai',name:'AR Theatre',city:'Chennai',state:'Tamil Nadu',type:'Premium Metro Screen',formats:['2D','Dolby Atmos'],price:300}]
const rows=['A','B','C','D','E','F','G','H','J','K']
const allSeats=rows.flatMap(row=>Array.from({length:12},(_,i)=>({id:`${row}${i+1}`,row,number:i+1,price:i<2||i>9?320:220})))
const events=[['Neon Nights','Music','Oct 18, 2026','7:30 PM','Hyderabad',799],['Comedy After Dark','Comedy','Oct 24, 2026','8:00 PM','Bengaluru',499],['Indie Film Fest','Movies','Nov 02, 2026','6:00 PM','Hyderabad',599]]

function App(){
const [movie,setMovie]=useState(null),[theater,setTheater]=useState(null),[seats,setSeats]=useState([]),[query,setQuery]=useState(''),[city,setCity]=useState('All'),[booking,setBooking]=useState(false),[confirmed,setConfirmed]=useState(false),[menu,setMenu]=useState(false)
const filteredMovies=useMemo(()=>movies.filter(m=>`${m.title} ${m.genre}`.toLowerCase().includes(query.toLowerCase())),[query])
const filteredTheaters=useMemo(()=>theaters.filter(t=>city==='All'||t.city===city),[city])
const occupied=useMemo(()=>{if(!movie||!theater)return new Set();let seed=0;for(const c of movie.id+theater.id)seed=(seed*31+c.charCodeAt(0))>>>0;const s=new Set();while(s.size<Math.floor(allSeats.length*.5)){seed=(seed*1664525+1013904223)>>>0;s.add(allSeats[seed%allSeats.length].id)}return s},[movie,theater])
const total=seats.reduce((n,id)=>n+(allSeats.find(s=>s.id===id)?.price||0),0)
const chooseMovie=m=>{setMovie(m);setTheater(null);setSeats([])}
const chooseTheater=t=>{setTheater(t);setSeats([]);setConfirmed(false);setBooking(true)}
const toggle=s=>{if(occupied.has(s.id))return;setSeats(p=>p.includes(s.id)?p.filter(x=>x!==s.id):[...p,s.id])}
const close=()=>{setBooking(false);setSeats([])}
return <div className="app"><header className="nav"><a className="brand" href="#top"><span className="brand-mark"><Ticket size={19}/></span>SHOW<span>TIME</span></a><nav className={menu?'nav-links open':'nav-links'}><a href="#movies">Movies</a><a href="#events">Events</a><a href="#how">How it works</a></nav><button className="icon-btn menu" onClick={()=>setMenu(!menu)}><User size={18}/></button></header>
<main id="top"><section className="hero"><div className="hero-copy"><p className="eyebrow">YOUR NIGHT. YOUR SEAT. YOUR SHOW.</p><h1>Make memories.<br/><em>Book the moment.</em></h1><p className="hero-text">Discover movies, choose your theatre and pick your exact seat with a live-style cinema experience.</p><a className="primary-btn" href="#movies">Book a movie <ChevronRight size={18}/></a></div><div className="hero-ticket"><div className="ticket-top"><span>SHOWTIME</span><span>LIVE</span></div><div className="ticket-art">STAY<br/><strong>CURIOUS</strong></div><div className="ticket-meta"><span>NOW SHOWING</span><span>HYD</span></div></div></section>
<section className="movies-section" id="movies"><div className="section-head"><div><p className="eyebrow">MOVIES · THEATRES · SEATS</p><h2>Tonight, pick a story.</h2><p className="section-sub">Movie → theatre → seats. Clicking a theatre opens the seating screen directly.</p></div><div className="search"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search movies..."/></div></div><div className="movie-layout"><div className="movie-list">{filteredMovies.map(m=><button className={`movie-card ${movie?.id===m.id?'chosen':''}`} key={m.id} onClick={()=>chooseMovie(m)}><div className={`poster ${m.tone}`}><span>{m.year}</span><strong>{m.title.split(' ').map(w=>w[0]).join('')}</strong><small>SHOWTIME EXPERIENCE</small></div><div className="movie-info"><div><h3>{m.title}</h3><p>{m.language} · {m.genre}</p></div><ChevronRight size={18}/></div></button>)}</div><div className="theater-panel">{movie?<><div className="selected-movie"><div className={`mini-poster ${movie.tone}`}>{movie.title.split(' ').map(w=>w[0]).join('')}</div><div><p className="eyebrow">SELECT A THEATRE</p><h3>{movie.title}</h3><p>Every theatre below opens its own seat map.</p></div></div><div className="city-tabs">{['All','Tenali','Kukatpally','Madhapur','Hyderabad','Vijayawada','Guntur','Visakhapatnam','Bengaluru','Chennai'].map(c=><button className={city===c?'active':''} key={c} onClick={()=>setCity(c)}>{c}</button>)}</div><div className="theater-list">{filteredTheaters.map(t=><button className="theater-card" key={t.id} onClick={()=>chooseTheater(t)}><div className="theater-icon"><Building2 size={20}/></div><div className="theater-main"><div className="theater-title"><h4>{t.name}</h4><span>{t.type}</span></div><p><MapPin size={13}/> {t.city}, {t.state}</p><div className="format-row">{t.formats.map(f=><small key={f}>{f}</small>)}</div></div><div className="theater-price">₹{t.price}<small> from</small></div></button>)}</div></>:<div className="theater-empty"><Film size={36}/><h3>Select a movie</h3><p>Theatre choices will appear here.</p></div>}</div></div></section>
<section className="discover" id="events"><div className="section-head"><div><p className="eyebrow">LIVE EXPERIENCES</p><h2>More than movies.</h2></div></div><div className="event-grid">{events.map(e=><article className="event-card" key={e[0]}><div className="event-art violet"><span>{e[1]}</span><b>{e[0].split(' ').map(x=>x[0]).join('')}</b><small>SHOWTIME</small></div><div className="event-body"><h3>{e[0]}</h3><p><CalendarDays size={15}/> {e[2]} · {e[3]}</p><p><MapPin size={15}/> {e[4]}</p><div className="card-bottom"><strong>₹{e[5]}<small> / person</small></strong></div></div></article>)}</div></section><section className="how" id="how"><div><p className="eyebrow">THREE SIMPLE STEPS</p><h2>Book without friction.</h2></div><div className="steps"><div><span>01</span><h3>Find your movie</h3><p>Search and select any movie.</p></div><div><span>02</span><h3>Choose a theatre</h3><p>Click the theatre itself to open its seating map immediately.</p></div><div><span>03</span><h3>Pick your seats</h3><p>About 50% are pre-occupied for a realistic cinema view. Only your selected seats are locked after confirmation.</p></div></div></section></main><footer><span>© 2026 ShowTime</span><span>Made for moments that matter.</span></footer>
{booking&&<div className="modal-backdrop" onClick={close}><div className="booking-modal cinema-modal" onClick={e=>e.stopPropagation()}>{confirmed?<div className="success"><div className="success-icon"><Check size={34}/></div><p className="eyebrow">BOOKING CONFIRMED</p><h2>Your seats are booked.</h2><p><strong>{movie?.title}</strong><br/>{theater?.name} · {theater?.city}<br/>Seats: <strong>{seats.join(', ')}</strong></p><button className="primary-btn" onClick={close}>Done</button></div>:<><div className="modal-head"><div><p className="eyebrow">{movie.title.toUpperCase()} · {theater.name.toUpperCase()}</p><h2>Choose your seats</h2><p><MapPin size={14}/> {theater.city} · <Clock3 size={14}/> Today · {theater.formats.join(' / ')}</p></div><button className="close" onClick={close}><X/></button></div><div className="occupancy"><span><span className="pulse-dot"/> LIVE-STYLE VIEW</span><strong>{occupied.size} / {allSeats.length} occupied</strong><small>About 50% pre-filled</small></div><div className="screen">SCREEN</div><div className="seat-map">{rows.map(r=><div className="seat-row" key={r}><label>{r}</label>{allSeats.filter(s=>s.row===r).map(s=><button key={s.id} disabled={occupied.has(s.id)} className={`seat ${occupied.has(s.id)?'booked':''} ${seats.includes(s.id)?'selected':''}`} onClick={()=>toggle(s)}>{s.number}</button>)}</div>)}</div><div className="legend"><span><i/>Available</span><span><i className="selected-dot"/>Your seat</span><span><i className="booked-dot"/>Occupied</span></div><div className="booking-footer"><div><small>{seats.length} seat{seats.length!==1?'s':''}</small><strong>₹{total.toLocaleString('en-IN')}</strong></div><button className="primary-btn" disabled={!seats.length} onClick={()=>setConfirmed(true)}>Confirm booking <Check size={17}/></button></div></>}</div></div>}</div>}
createRoot(document.getElementById('root')).render(<App/>)
